"""Seed script for Shoptegrity.

Populates initial categories, major corporations, cited evidence,
verified alternatives, small food makers (including the U.S. tea growers proof),
local places, and dollar flow profiles.
"""

from api.app.db.session import SessionLocal, init_db
from api.app.models.core import (
    Entity,
    Brand,
    SpendCategory,
    Evidence,
    Alternative,
    FlowProfile,
    Place,
    Maker,
)


def run_seed():
    init_db()
    db = SessionLocal()

    # Clear existing data
    db.query(Alternative).delete()
    db.query(Maker).delete()
    db.query(Place).delete()
    db.query(FlowProfile).delete()
    db.query(Evidence).delete()
    db.query(Brand).delete()
    db.query(Entity).delete()
    db.query(SpendCategory).delete()
    db.commit()

    print("Populating Spend Categories...")
    cats = [
        SpendCategory(
            id="cat-banking",
            name="Banking & Finance",
            slug="banking",
            tier=1,
            avg_annual_spend=4200.0,
            swap_difficulty="easy",
            saves_money=True,
            description="Checking, savings, mortgages, and loans. Moving from megabanks to credit unions stops financing extraction.",
        ),
        SpendCategory(
            id="cat-grocery",
            name="Grocery & Food",
            slug="grocery",
            tier=1,
            avg_annual_spend=8400.0,
            swap_difficulty="easy",
            saves_money=True,
            description="Pantry, produce, dairy, and meat. Reroutes grocery dollars to farmer co-ops and local growers.",
        ),
        SpendCategory(
            id="cat-clothing",
            name="Clothing & Apparel",
            slug="clothing",
            tier=1,
            avg_annual_spend=2200.0,
            swap_difficulty="moderate",
            saves_money=True,
            description="Garments and footwear. Prioritizes durability, repair, thrift, and fair trade labor.",
        ),
        SpendCategory(
            id="cat-insurance",
            name="Insurance",
            slug="insurance",
            tier=1,
            avg_annual_spend=3100.0,
            swap_difficulty="moderate",
            saves_money=True,
            description="Auto and home insurance. Swapping to mutual and policyholder-owned insurers.",
        ),
        SpendCategory(
            id="cat-hardware",
            name="Hardware & Home Services",
            slug="hardware",
            tier=1,
            avg_annual_spend=1500.0,
            swap_difficulty="easy",
            saves_money=False,
            description="Tools, plumbing, HVAC, and repairs. Supporting genuine local owner-operators and co-ops.",
        ),
    ]
    for c in cats:
        db.add(c)
    db.commit()

    print("Populating Entities...")
    entities = [
        # --- Conventional Megacorps ---
        Entity(
            id="ent-genmills",
            name="General Mills, Inc.",
            slug="general-mills",
            kind="company",
            ownership_type="public",
            hq_city="Minneapolis",
            hq_state="MN",
            is_public=True,
            ticker="GIS",
            website="https://www.generalmills.com",
            ceo_pay_ratio=280.0,
            capital_extraction_ratio=0.88,
            locality_tier="multinational",
            notes="Owns Annie's Homegrown, Cascadian Farm, Cheerios, Betty Crocker.",
        ),
        Entity(
            id="ent-nestle",
            name="Nestlé S.A.",
            slug="nestle",
            kind="company",
            ownership_type="public",
            hq_city="Vevey",
            hq_state="Vaud",
            hq_country="Switzerland",
            is_public=True,
            ticker="NSRGY",
            website="https://www.nestle.com",
            ceo_pay_ratio=310.0,
            capital_extraction_ratio=0.92,
            locality_tier="multinational",
            notes="World's largest food conglomerate. Heavy shareholder buybacks and groundwater extraction history.",
        ),
        Entity(
            id="ent-wellsfargo",
            name="Wells Fargo & Company",
            slug="wells-fargo",
            kind="company",
            ownership_type="public",
            hq_city="San Francisco",
            hq_state="CA",
            is_public=True,
            ticker="WFC",
            website="https://www.wellsfargo.com",
            ceo_pay_ratio=325.0,
            capital_extraction_ratio=0.85,
            locality_tier="national_public",
            notes="Repeated consumer protection and fake account violations from CFPB.",
        ),
        Entity(
            id="ent-tyson",
            name="Tyson Foods, Inc.",
            slug="tyson-foods",
            kind="company",
            ownership_type="public",
            hq_city="Springdale",
            hq_state="AR",
            is_public=True,
            ticker="TSN",
            website="https://www.tysonfoods.com",
            ceo_pay_ratio=260.0,
            capital_extraction_ratio=0.78,
            locality_tier="national_public",
            notes="Industrial meat processor with severe OSHA safety and EPA wastewater violations.",
        ),
        Entity(
            id="ent-shein",
            name="Roadget Business Pte. Ltd. (Shein)",
            slug="shein",
            kind="company",
            ownership_type="national_private",
            hq_city="Singapore",
            hq_state=None,
            hq_country="Singapore",
            is_public=False,
            website="https://www.shein.com",
            ceo_pay_ratio=None,
            capital_extraction_ratio=None,
            locality_tier="multinational",
            notes="Ultra-fast fashion, severe labor conditions reported by investigative journalists.",
        ),
        Entity(
            id="ent-bigelow",
            name="R.C. Bigelow, Inc.",
            slug="bigelow-tea",
            kind="company",
            ownership_type="national_private",
            hq_city="Fairfield",
            hq_state="CT",
            is_public=False,
            website="https://www.bigelowtea.com",
            ceo_pay_ratio=45.0,
            capital_extraction_ratio=0.35,
            locality_tier="national_private",
            notes="Family-owned tea company. Acquired Charleston Tea Garden in 2003.",
        ),
        Entity(
            id="ent-apex-pe",
            name="Apex Service Partners",
            slug="apex-service-partners",
            kind="pe_firm",
            ownership_type="private_equity",
            hq_city="Tampa",
            hq_state="FL",
            is_public=False,
            website="https://www.apexservicepartners.com",
            ceo_pay_ratio=None,
            capital_extraction_ratio=1.40,
            locality_tier="private_equity_rollup",
            notes="PE rollup platform actively buying local HVAC, plumbing, and electrical contractors.",
        ),

        # --- Ethical & High-Integrity Alternatives ---
        Entity(
            id="ent-equalexchange",
            name="Equal Exchange",
            slug="equal-exchange",
            kind="cooperative",
            ownership_type="worker_coop",
            hq_city="West Bridgewater",
            hq_state="MA",
            is_public=False,
            website="https://equalexchange.coop",
            ceo_pay_ratio=4.0,
            capital_extraction_ratio=0.05,
            locality_tier="regional_independent",
            notes="Worker-owned cooperative with 1:1 voting. 100% fair trade and organic coffee, tea, and chocolate.",
        ),
        Entity(
            id="ent-organicvalley",
            name="CROPP Cooperative (Organic Valley)",
            slug="organic-valley",
            kind="cooperative",
            ownership_type="producer_coop",
            hq_city="La Farge",
            hq_state="WI",
            is_public=False,
            website="https://www.organicvalley.coop",
            ceo_pay_ratio=12.0,
            capital_extraction_ratio=0.10,
            locality_tier="regional_independent",
            notes="Farmer-owned cooperative representing over 1,700 organic family farms across the Midwest.",
        ),
        Entity(
            id="ent-kingarthur",
            name="King Arthur Baking Company",
            slug="king-arthur-baking",
            kind="company",
            ownership_type="esop_100",
            hq_city="Norwich",
            hq_state="VT",
            is_public=False,
            website="https://www.kingarthurbaking.com",
            ceo_pay_ratio=14.0,
            capital_extraction_ratio=0.15,
            locality_tier="national_private",
            notes="100% employee-owned ESOP and founding Certified B Corporation.",
        ),
        Entity(
            id="ent-bobsredmill",
            name="Bob's Red Mill Natural Foods",
            slug="bobs-red-mill",
            kind="company",
            ownership_type="esop_100",
            hq_city="Milwaukie",
            hq_state="OR",
            is_public=False,
            website="https://www.bobsredmill.com",
            ceo_pay_ratio=8.0,
            capital_extraction_ratio=0.10,
            locality_tier="national_private",
            notes="Transferred 100% ownership to employees via ESOP trust.",
        ),
        Entity(
            id="ent-drbronners",
            name="All-One God Faith, Inc. (Dr. Bronner's)",
            slug="dr-bronners",
            kind="company",
            ownership_type="purpose_trust",
            hq_city="Vista",
            hq_state="CA",
            is_public=False,
            website="https://www.drbronner.com",
            ceo_pay_ratio=5.0,
            capital_extraction_ratio=0.12,
            locality_tier="national_private",
            notes="Certified B Corp with executive compensation legally capped at 5x lowest paid worker.",
        ),
        Entity(
            id="ent-affinityplus",
            name="Affinity Plus Federal Credit Union",
            slug="affinity-plus",
            kind="cooperative",
            ownership_type="credit_union",
            hq_city="St. Paul",
            hq_state="MN",
            is_public=False,
            website="https://www.affinityplus.org",
            ceo_pay_ratio=16.0,
            capital_extraction_ratio=0.0,
            locality_tier="owner_operated_local",
            notes="Member-owned not-for-profit financial cooperative chartered in Minnesota.",
        ),
        Entity(
            id="ent-patagonia",
            name="Patagonia, Inc.",
            slug="patagonia",
            kind="company",
            ownership_type="purpose_trust",
            hq_city="Ventura",
            hq_state="CA",
            is_public=False,
            website="https://www.patagonia.com",
            ceo_pay_ratio=18.0,
            capital_extraction_ratio=0.0,
            locality_tier="national_private",
            notes="100% of voting stock transferred to Patagonia Purpose Trust; 100% of nonvoting stock to Holdfast Collective.",
        ),
    ]

    for ent in entities:
        db.add(ent)
    db.commit()

    print("Populating Brands...")
    brands = [
        # Conventional
        Brand(
            id="br-annies",
            name="Annie's Homegrown",
            slug="annies-homegrown",
            entity_id="ent-genmills",
            description="Organic mac and cheese and snacks, marketed as wholesome, acquired by General Mills in 2014 for $820M.",
            website="https://www.annies.com",
            category_tags=["grocery", "pasta", "snacks"],
        ),
        Brand(
            id="br-cheerios",
            name="Cheerios",
            slug="cheerios",
            entity_id="ent-genmills",
            description="Flagship cereal brand of General Mills.",
            website="https://www.cheerios.com",
            category_tags=["grocery", "cereal"],
        ),
        Brand(
            id="br-purelife",
            name="Nestlé Pure Life / Bottled Water",
            slug="pure-life-water",
            entity_id="ent-nestle",
            description="Bottled water extracted from municipal springs and aquifers.",
            website="https://www.nestlepurelife.com",
            category_tags=["grocery", "water"],
        ),
        Brand(
            id="br-wellsfargo",
            name="Wells Fargo Consumer Banking",
            slug="wells-fargo-banking",
            entity_id="ent-wellsfargo",
            description="Retail banking, credit cards, and mortgage services.",
            website="https://www.wellsfargo.com",
            category_tags=["banking"],
        ),
        Brand(
            id="br-shein",
            name="SHEIN Fast Fashion",
            slug="shein-clothing",
            entity_id="ent-shein",
            description="Ultra-fast fashion producing thousands of ultra-cheap synthetic garments daily.",
            website="https://www.shein.com",
            category_tags=["clothing"],
        ),
        Brand(
            id="br-bigelow",
            name="Bigelow Tea",
            slug="bigelow-tea-brand",
            entity_id="ent-bigelow",
            description="Nationwide tea brand. Owns Charleston Tea Garden in South Carolina.",
            website="https://www.bigelowtea.com",
            category_tags=["grocery", "tea"],
        ),

        # Alternatives
        Brand(
            id="br-organicvalley",
            name="Organic Valley Dairy",
            slug="organic-valley-dairy",
            entity_id="ent-organicvalley",
            description="Farmer-owned organic milk, cheese, and butter.",
            website="https://www.organicvalley.coop",
            category_tags=["grocery", "dairy"],
        ),
        Brand(
            id="br-equalexchange",
            name="Equal Exchange Organic Tea & Coffee",
            slug="equal-exchange-tea",
            entity_id="ent-equalexchange",
            description="Worker-owned cooperative organic teas sourced directly from small farmer cooperatives worldwide.",
            website="https://equalexchange.coop",
            category_tags=["grocery", "tea", "coffee"],
        ),
        Brand(
            id="br-kingarthur",
            name="King Arthur Baking",
            slug="king-arthur-flour",
            entity_id="ent-kingarthur",
            description="100% employee-owned flours, baking mixes, and pantry staples.",
            website="https://www.kingarthurbaking.com",
            category_tags=["grocery", "baking"],
        ),
        Brand(
            id="br-bobsredmill",
            name="Bob's Red Mill Grains & Oats",
            slug="bobs-red-mill-brand",
            entity_id="ent-bobsredmill",
            description="Employee-owned stone-ground grains, oats, and cereal alternatives.",
            website="https://www.bobsredmill.com",
            category_tags=["grocery", "cereal", "grains"],
        ),
        Brand(
            id="br-affinityplus",
            name="Affinity Plus Credit Union Accounts",
            slug="affinity-plus-banking",
            entity_id="ent-affinityplus",
            description="Member-owned no-fee checking, savings, and local mortgages.",
            website="https://www.affinityplus.org",
            category_tags=["banking"],
        ),
        Brand(
            id="br-patagonia",
            name="Patagonia Outdoor Apparel",
            slug="patagonia-apparel",
            entity_id="ent-patagonia",
            description="Durable, repair-guaranteed clothing owned by a purpose trust for the planet.",
            website="https://www.patagonia.com",
            category_tags=["clothing"],
        ),
    ]

    for b in brands:
        db.add(b)
    db.commit()

    print("Populating Cited Evidence...")
    evidence_items = [
        Evidence(
            entity_id="ent-genmills",
            dimension="ownership",
            fact_text="Publicly traded corporation (NYSE: GIS) held predominantly by institutional asset managers.",
            source_url="https://www.sec.gov/edgar/browse/?CIK=40704",
            source_name="SEC Form 10-K",
            source_type="sec_edgar",
            retrieved_at="2026-09-01",
            impact=0,
        ),
        Evidence(
            entity_id="ent-genmills",
            dimension="capital_extraction",
            fact_text="General Mills returned $2.4B in stock buybacks and dividends in FY2024, representing 88% of net earnings.",
            source_url="https://investors.generalmills.com/financial-information/annual-reports",
            source_name="General Mills 2024 Annual Report",
            source_type="sec_edgar",
            retrieved_at="2026-09-01",
            impact=-1,
        ),
        Evidence(
            entity_id="ent-genmills",
            dimension="pay_equity",
            fact_text="CEO Jeff Harmening total compensation was $16.3M; median employee compensation was $58,200 (Ratio: 280 to 1).",
            source_url="https://www.sec.gov/ix?doc=/Archives/edgar/data/40704/000119312524199587/d798363ddef14a.htm",
            source_name="SEC DEF 14A Proxy Statement Item 402(u)",
            source_type="sec_edgar",
            retrieved_at="2026-09-01",
            impact=-2,
        ),
        Evidence(
            entity_id="ent-wellsfargo",
            dimension="labor",
            fact_text="CFPB ordered Wells Fargo to pay $3.7B in customer redress and penalties over widespread consumer account abuses.",
            source_url="https://www.consumerfinance.gov/about-us/newsroom/cfpb-orders-wells-fargo-to-pay-37-billion-for-widespread-mismanagement/",
            source_name="Consumer Financial Protection Bureau Enforcement Order",
            source_type="osha",
            retrieved_at="2026-09-01",
            impact=-2,
        ),
        Evidence(
            entity_id="ent-equalexchange",
            dimension="ownership",
            fact_text="Incorporated as a worker-owned cooperative under Massachusetts law; every worker-owner holds exactly one share and one vote.",
            source_url="https://equalexchange.coop/our-story/how-we-work",
            source_name="Equal Exchange Articles of Organization",
            source_type="state_registry",
            retrieved_at="2026-09-01",
            impact=2,
        ),
        Evidence(
            entity_id="ent-equalexchange",
            dimension="pay_equity",
            fact_text="Internal bylaws legally cap top executive compensation at 4:1 compared to the lowest-paid full-time employee.",
            source_url="https://equalexchange.coop/our-story/fair-trade",
            source_name="Equal Exchange Annual Transparency Report",
            source_type="certifier",
            retrieved_at="2026-09-01",
            impact=2,
        ),
        Evidence(
            entity_id="ent-organicvalley",
            dimension="ownership",
            fact_text="CROPP Cooperative is 100% owned by its 1,700+ farmer members with democratic one-farm, one-vote governance.",
            source_url="https://www.organicvalley.coop/about-us/our-cooperative/",
            source_name="CROPP Cooperative Annual Report",
            source_type="certifier",
            retrieved_at="2026-09-01",
            impact=2,
        ),
        Evidence(
            entity_id="ent-affinityplus",
            dimension="ownership",
            fact_text="Federally insured credit union owned 100% by its member depositors. NCUA Charter #62608.",
            source_url="https://mapping.ncua.gov/CreditUnionDetails/62608",
            source_name="National Credit Union Administration (NCUA)",
            source_type="ncua",
            retrieved_at="2026-09-01",
            impact=2,
        ),
        Evidence(
            entity_id="ent-apex-pe",
            dimension="ownership",
            fact_text="Private equity platform company backed by Alpine Investors; acquired over 85 regional residential service contractors.",
            source_url="https://www.businesswire.com/news/home/20230509005391/en/Apex-Service-Partners",
            source_name="Business Wire Press Release",
            source_type="trade_press",
            retrieved_at="2026-09-01",
            impact=-2,
        ),
    ]

    for ev in evidence_items:
        db.add(ev)
    db.commit()

    print("Populating Alternatives...")
    alts = [
        Alternative(
            from_brand_id="br-annies",
            to_brand_id="br-organicvalley",
            spend_category_id="cat-grocery",
            rationale="Swaps General Mills packaged mac & cheese for farmer-owned cooperative organic cheese and whole food ingredients.",
            price_band="$$",
            where_to_buy="Local Food Co-ops, natural grocery stores, and major supermarkets.",
            savings_estimate="Comparable cost; 65% of dollar reaches farmers vs 14% at General Mills.",
        ),
        Alternative(
            from_brand_id="br-cheerios",
            to_brand_id="br-bobsredmill",
            spend_category_id="cat-grocery",
            rationale="100% employee-owned whole grain rolled oats swap out multinational processed boxed cereals.",
            price_band="$$",
            where_to_buy="Co-ops, bulk food bins, and regional grocers.",
            savings_estimate="Saves up to $120/year when purchased in bulk.",
        ),
        Alternative(
            from_brand_id="br-wellsfargo",
            to_brand_id="br-affinityplus",
            spend_category_id="cat-banking",
            rationale="Moving deposits from a repeat-violator megabank to a member-owned Minnesota credit union stops predatory extraction.",
            price_band="$",
            where_to_buy="Online, statewide branches, and 30,000+ fee-free CO-OP ATMs.",
            savings_estimate="Saves ~$120/year in account maintenance fees + lower loan interest rates.",
        ),
        Alternative(
            from_brand_id="br-shein",
            to_brand_id="br-patagonia",
            spend_category_id="cat-clothing",
            rationale="Replaces disposable ultra-fast fashion with repair-for-life garments owned by a climate purpose trust.",
            price_band="$$$",
            where_to_buy="Patagonia stores, Worn Wear (used), or verified retailers.",
            savings_estimate="Higher upfront cost, but saves hundreds over 5-10 years due to free lifetime repair.",
        ),
        Alternative(
            from_brand_id="br-bigelow",
            to_brand_id="br-equalexchange",
            spend_category_id="cat-grocery",
            rationale="Swaps mid-size private brand blending imported leaf for worker-owned, direct fair-trade organic tea cooperatives.",
            price_band="$$",
            where_to_buy="Natural food co-ops and Equal Exchange online store.",
            savings_estimate="Price competitive per cup.",
        ),
    ]

    for a in alts:
        db.add(a)
    db.commit()

    print("Populating Dollar Flow Profiles...")
    flows = [
        FlowProfile(
            id="flow-grocery-conventional",
            spend_category_id="cat-grocery",
            option_type="conventional",
            display_title="Conventional Supermarket Chain",
            year=2024,
            nodes_json={
                "input_spend": 100.0,
                "splits": [
                    {"label": "Farm & Producer Share", "amount": 14.70, "color": "#16a34a"},
                    {"label": "Frontline Worker Wages", "amount": 12.50, "color": "#0284c7"},
                    {"label": "Processing, Transport & Packaging", "amount": 28.30, "color": "#f59e0b"},
                    {"label": "Corporate Marketing & Advertising", "amount": 8.50, "color": "#dc2626"},
                    {"label": "Store Rent, Operations & Energy", "amount": 16.00, "color": "#64748b"},
                    {"label": "Executive Compensation", "amount": 4.20, "color": "#9333ea"},
                    {"label": "Shareholder Dividends & Buybacks", "amount": 15.80, "color": "#b91c1c"},
                ],
            },
            summary_text="At a conventional supermarket chain, roughly $15.80 of your $100 leaves the community directly into shareholder dividends and stock buybacks, while the actual food grower receives under $15.",
            source_notes="USDA ERS Food Dollar Series (2024) + Average SEC 10-K gross margin breakdown of publicly traded grocers.",
        ),
        FlowProfile(
            id="flow-grocery-coop",
            spend_category_id="cat-grocery",
            option_type="alternative",
            display_title="Member-Owned Food Cooperative",
            year=2024,
            nodes_json={
                "input_spend": 100.0,
                "splits": [
                    {"label": "Local & Regional Farm Share", "amount": 42.00, "color": "#16a34a"},
                    {"label": "Living Wage Store Staff", "amount": 28.50, "color": "#0284c7"},
                    {"label": "Distribution & Green Operations", "amount": 18.00, "color": "#64748b"},
                    {"label": "Member Patronage Dividends", "amount": 6.50, "color": "#059669"},
                    {"label": "Community Education & Grants", "amount": 5.00, "color": "#2563eb"},
                    {"label": "Shareholder Extraction", "amount": 0.00, "color": "#94a3b8"},
                ],
            },
            summary_text="At a food cooperative, zero dollars leak to outside public shareholders. Local farmers receive roughly 3x more per dollar spent, and operational surplus returns to shoppers as member dividends.",
            source_notes="National Co+op Grocers (NCG) Food Co-op Impact Report.",
        ),
        FlowProfile(
            id="flow-banking-conventional",
            spend_category_id="cat-banking",
            option_type="conventional",
            display_title="Megabank (e.g. Wells Fargo)",
            year=2024,
            nodes_json={
                "input_spend": 100.0,
                "splits": [
                    {"label": "Shareholder Profits & Buybacks", "amount": 38.00, "color": "#b91c1c"},
                    {"label": "Executive Compensation & Bonuses", "amount": 14.50, "color": "#9333ea"},
                    {"label": "Fossil Fuel & Extractive Lending", "amount": 25.00, "color": "#ea580c"},
                    {"label": "Branch Operations & Teller Pay", "amount": 15.50, "color": "#0284c7"},
                    {"label": "Customer Interest Paid Back", "amount": 7.00, "color": "#16a34a"},
                ],
            },
            summary_text="Megabanks deploy the majority of customer deposit margins to institutional buybacks and multinational corporate lending.",
            source_notes="SEC Form 10-K & Rainforest Action Network Banking on Climate Chaos Report.",
        ),
        FlowProfile(
            id="flow-banking-coop",
            spend_category_id="cat-banking",
            option_type="alternative",
            display_title="Community Credit Union",
            year=2024,
            nodes_json={
                "input_spend": 100.0,
                "splits": [
                    {"label": "Higher Savings Yields & Lower Rates", "amount": 42.00, "color": "#16a34a"},
                    {"label": "Local Mortgages & Small Business Loans", "amount": 35.00, "color": "#059669"},
                    {"label": "Staff Living Wages & Benefits", "amount": 16.00, "color": "#0284c7"},
                    {"label": "Capital Reserves & Tech Upgrade", "amount": 7.00, "color": "#64748b"},
                    {"label": "Shareholder Extraction", "amount": 0.00, "color": "#94a3b8"},
                ],
            },
            summary_text="Credit unions are not-for-profit cooperatives: profit is returned to member depositors as lower borrowing fees, better interest rates, and local community lending.",
            source_notes="NCUA Financial Performance Reports.",
        ),
    ]

    for f in flows:
        db.add(f)
    db.commit()

    print("Populating Local Places & Food Makers (including U.S. Tea Proof)...")
    places = [
        # Twin Cities Co-ops & Markets
        Place(
            id="plc-wedge",
            name="Wedge Community Co-op (Lyndale)",
            slug="wedge-coop-lyndale",
            category="food_coop",
            address="2105 Lyndale Ave S",
            city="Minneapolis",
            state="MN",
            postal_code="55405",
            lat=44.9625,
            lon=-93.2882,
            phone="(612) 871-3993",
            website="https://tcecmakers.com",
            ownership_tier=1,
            flags=["coop", "snap_ebt", "organic"],
            verified_locally=True,
            verified_how="State cooperative registration & National Co+op Grocers verified member",
            hours="8:00 AM - 9:00 PM Daily",
        ),
        Place(
            id="plc-seward",
            name="Seward Community Co-op (Franklin)",
            slug="seward-coop-franklin",
            category="food_coop",
            address="2823 E Franklin Ave",
            city="Minneapolis",
            state="MN",
            postal_code="55406",
            lat=44.9631,
            lon=-93.2305,
            phone="(612) 338-2465",
            website="https://seward.coop",
            ownership_tier=1,
            flags=["coop", "snap_ebt", "organic"],
            verified_locally=True,
            verified_how="Consumer cooperative incorporation filings",
            hours="8:00 AM - 9:00 PM Daily",
        ),
        Place(
            id="plc-millcity",
            name="Mill City Farmers Market",
            slug="mill-city-farmers-market",
            category="farmers_market",
            address="704 S 2nd St",
            city="Minneapolis",
            state="MN",
            postal_code="55401",
            lat=44.9785,
            lon=-93.2568,
            website="https://millcityfarmersmarket.org",
            ownership_tier=1,
            flags=["snap_ebt", "organic"],
            verified_locally=True,
            verified_how="Direct vendor verification, 100% grower-operated policy",
            hours="Saturdays 8:00 AM - 1:00 PM",
            season="May through October (indoor winter markets monthly)",
        ),
        Place(
            id="plc-tangletown",
            name="Tangletown Farm Stand & CSA",
            slug="tangletown-farm",
            category="csa",
            address="5353 Nicollet Ave",
            city="Minneapolis",
            state="MN",
            postal_code="55419",
            lat=44.9056,
            lon=-93.2783,
            website="https://tangletowngardens.com",
            ownership_tier=1,
            flags=["organic", "makes_own"],
            verified_locally=True,
            verified_how="Direct farm ownership in Plato, MN",
        ),
        Place(
            id="plc-cu-stpaul",
            name="Affinity Plus Credit Union (St. Paul Branch)",
            slug="affinity-plus-stpaul",
            category="credit_union",
            address="175 W Lafayette Frontage Rd",
            city="St. Paul",
            state="MN",
            postal_code="55107",
            lat=44.9421,
            lon=-93.0825,
            phone="(800) 322-7228",
            website="https://www.affinityplus.org",
            ownership_tier=1,
            flags=["coop"],
            verified_locally=True,
            verified_how="NCUA Charter verification",
            hours="M-F 9:00 AM - 5:00 PM",
        ),

        # Disguised Rollup (PE) vs Real Local Trade
        Place(
            id="plc-pe-plumbing",
            name="Minneapolis Metro Plumbing & Heating",
            slug="minneapolis-metro-plumbing",
            category="plumber",
            address="1420 University Ave W",
            city="St. Paul",
            state="MN",
            postal_code="55104",
            lat=44.9556,
            lon=-93.1612,
            phone="(651) 555-0199",
            entity_id="ent-apex-pe",
            ownership_tier=6,
            flags=["rollup_disguised", "recently_acquired"],
            verified_locally=True,
            verified_how="Acquired by Apex Service Partners (Private Equity). Legacy local name retained.",
        ),
        Place(
            id="plc-local-electric",
            name="Twin Cities Solar & Electrical Co-op",
            slug="twin-cities-solar-coop",
            category="electrician",
            address="312 Central Ave SE",
            city="Minneapolis",
            state="MN",
            postal_code="55414",
            lat=44.9862,
            lon=-93.2531,
            ownership_tier=1,
            flags=["coop"],
            verified_locally=True,
            verified_how="Worker cooperative business filings with Minnesota Secretary of State",
        ),

        # U.S. Tea Proof (from Market Analysis)
        Place(
            id="plc-charleston-tea",
            name="Charleston Tea Garden",
            slug="charleston-tea-garden",
            category="farm_stand",
            address="6617 Maybank Hwy",
            city="Wadmalaw Island",
            state="SC",
            postal_code="29487",
            lat=32.6179,
            lon=-80.1989,
            website="https://charlestonteagarden.com",
            entity_id="ent-bigelow",
            ownership_tier=5,  # Owned by Bigelow Tea (national private)
            flags=["makes_own"],
            verified_locally=True,
            verified_how="Owned by R.C. Bigelow Inc since 2003 auction; verified U.S. grown Charleston leaf",
        ),
        Place(
            id="plc-tablerock-tea",
            name="Table Rock Tea Company",
            slug="table-rock-tea",
            category="farm_stand",
            address="156 Table Rock Rd",
            city="Pickens",
            state="SC",
            postal_code="29671",
            lat=34.9812,
            lon=-82.7214,
            website="https://tablerocktea.com",
            ownership_tier=1,
            flags=["makes_own", "organic"],
            verified_locally=True,
            verified_how="Family owner-operated independent tea farm. U.S. League of Tea Growers member.",
        ),
        Place(
            id="plc-camellia-forest",
            name="Camellia Forest Tea Gardens",
            slug="camellia-forest-tea",
            category="farm_stand",
            address="6201 NC Hwy 86 N",
            city="Chapel Hill",
            state="NC",
            postal_code="27516",
            lat=36.0312,
            lon=-79.0815,
            website="https://teafarm.camforest.com",
            ownership_tier=1,
            flags=["makes_own", "organic"],
            verified_locally=True,
            verified_how="Small grower-processor verified by North Carolina Department of Agriculture",
        ),
    ]

    for p in places:
        db.add(p)
    db.commit()

    makers = [
        Maker(
            id="mkr-tablerock",
            name="Table Rock Tea Farm & Artisans",
            place_id="plc-tablerock-tea",
            products=["Artisan Black Tea", "Green Tea Leaf", "Herbal Blends"],
            makes_own=True,
            makes_own_evidence="Grows, harvests, and crafts leaf entirely on-site in the Blue Ridge foothills.",
            certifications=["Naturally Grown", "U.S. League of Tea Growers Certified"],
            sourcing_ladder_tier=3,
            where_to_buy="Direct from farm web store or on-site visitor center.",
            direct_order_url="https://tablerocktea.com/shop",
        ),
        Maker(
            id="mkr-camellia",
            name="Camellia Forest Tea Maker",
            place_id="plc-camellia-forest",
            products=["Small-Batch Green Tea", "White Tea", "Tea Plants"],
            makes_own=True,
            makes_own_evidence="Propagates cold-hardy Camellia sinensis varieties and hand-processes all teas on farm.",
            certifications=["Certified Organic Farm"],
            sourcing_ladder_tier=3,
            where_to_buy="Farm web store and regional seasonal markets.",
            direct_order_url="https://teafarm.camforest.com",
        ),
        Maker(
            id="mkr-charleston",
            name="American Classic Tea (Charleston Tea Garden)",
            place_id="plc-charleston-tea",
            products=["American Classic Black Tea", "Plantation Peach Tea"],
            makes_own=True,
            makes_own_evidence="Made with tea leaves cultivated on Wadmalaw Island; owned by R.C. Bigelow Inc.",
            certifications=["South Carolina Certified Grown"],
            sourcing_ladder_tier=5,
            where_to_buy="Charleston gift shop, online, and select grocery stores.",
            direct_order_url="https://charlestonteagarden.com",
        ),
        Maker(
            id="mkr-tangletown",
            name="Tangletown Produce & Heritage Pastures",
            place_id="plc-tangletown",
            products=["Heirloom Tomatoes", "Pastured Eggs", "Seasonal Greens", "Honey"],
            makes_own=True,
            makes_own_evidence="Grown on 140-acre regenerative farm in Plato, MN; delivered direct to Minneapolis.",
            certifications=["Regenerative Practices", "Minnesota Grown"],
            sourcing_ladder_tier=3,
            where_to_buy="CSA membership and Minneapolis farm store.",
            direct_order_url="https://tangletowngardens.com/csa",
        ),
    ]

    for m in makers:
        db.add(m)
    db.commit()

    # Seed top 2,000 brands database and export JSON
    from pipeline.top2000_brands import seed_top2000_db, export_top2000_json
    seed_top2000_db(db)
    export_top2000_json()

    db.close()
    print("Database successfully seeded with Shoptegrity core data & top 2,000 brands!")


if __name__ == "__main__":
    run_seed()
